### ISSUE TITLE
5.91因为证书错误，win10无法安装

### ISSUE THREAD

**Issue by RwangToo** [u2s1/winrarsc#1]
更新的地址
https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20200827/wrr/wrar591sc.exe
https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20200827/wrr/winrar-x64-591sc.exe

**Comment by u2s1** [comment]
已经修改，感谢提供地址

**Comment by 1265578519** [comment]
谢谢分享

**Comment by RwangToo** [comment]
6.0
https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20201210/wrr/winrar-x64-600sc.exe
https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20201210/wrr/wrar600sc.exe

**Comment by u2s1** [comment]
> 6.0
> https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20201210/wrr/winrar-x64-600sc.exe
> https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20201210/wrr/wrar600sc.exe

已经修改，再次感谢提供地址

**Comment by RwangToo** [comment]
6.01
32位
https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20210414/rrlb/wrar601sc.exe
https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20210414/wrr/wrar601sc.exe
64位
https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20210414/rrlb/winrar-x64-601sc.exe
https://www.win-rar.com/fileadmin/winrar-versions/sc/sc20210414/wrr/winrar-x64-601sc.exe

两个链接下载下来大小不一样，不知道wrr和rrlb的区别

**Comment by 1265578519** [comment]
> 两个链接下载下来大小不一样，不知道wrr和rrlb的区别

wrr是开发版，wrr是发行正式版
